"""The Patterns themselves. The engine imports none of these — a pipeline names them."""

from .advancing_legs import AdvancingLeg, AdvancingLegsPattern, advancing_legs, trim_tail
from .bar_gap import BarGap, BarGapPattern, bar_gaps
from .bars import BarMark, BarsPattern
from .general_direction import GeneralDirection, GeneralDirectionPattern, general_direction
from .leg_extremes import (
    ExtremeType,
    LegExtremes,
    LegExtremesPattern,
    LegPoint,
    extreme_points,
)
from .leg_processor import Leg, LegPattern, bar_positions, position_of, split_legs
from .leg_reversals import LegBar, LegReversals, LegReversalsPattern, marked_bars
from .leg_window import LegWindow, LegWindowPattern, split_leg_windows
from .line_relations import (
    NO_LINES,
    OPPOSITE,
    Line,
    LineRelation,
    LineRelationsPattern,
    PinnedLines,
    PriceAt,
    RelationKind,
    Side,
    Wick,
    breaks_out,
    constantly,
    line_relations,
    relations_of,
    side_of,
    touches,
)
from .line_respect import (
    LineRespect,
    LineRespectPattern,
    line_respects,
    respected_side,
    undone_breakouts,
)
from .nested_legs import NestedLegs, NestedLegsPattern, nested_legs
# Re-exported from here rather than from `leg_reversals`, where they used to live: they are the
# arithmetic two Patterns share, and the names a pipeline imports must not move because of it.
from .reversal_filters import (
    AVERAGE_WINDOW,
    DEFAULT_EXPANSION,
    DEFAULT_K,
    DEFAULT_SIMILARITY,
    MarkType,
    adjacent,
    alike,
    dominates,
    expands,
    implied_body_min,
    nests,
    reverses,
)
from .simple_leg import LegMark, PbMark, SimpleLegPattern
from .trend_lines import LineEnd, TrendLine, TrendLinesPattern, clear, leg_ends, trend_lines
from .trend_relations import (
    NO_TRENDS,
    PinnedTrend,
    PinnedTrends,
    TrendRelationsPattern,
    price_at,
    resolver,
    trend_relations,
)
from .zigzag import ZigZagIndidicator, ZigZagPattern, ZigZagPivot

__all__ = [
    "AVERAGE_WINDOW",
    "AdvancingLeg",
    "AdvancingLegsPattern",
    "BarGap",
    "BarGapPattern",
    "BarMark",
    "BarsPattern",
    "DEFAULT_EXPANSION",
    "DEFAULT_K",
    "DEFAULT_SIMILARITY",
    "ExtremeType",
    "GeneralDirection",
    "GeneralDirectionPattern",
    "Leg",
    "LegBar",
    "LegExtremes",
    "LegExtremesPattern",
    "LegMark",
    "LegPattern",
    "LegPoint",
    "LegReversals",
    "LegReversalsPattern",
    "LegWindow",
    "LegWindowPattern",
    "Line",
    "LineEnd",
    "LineRelation",
    "LineRelationsPattern",
    "LineRespect",
    "LineRespectPattern",
    "MarkType",
    "NO_LINES",
    "NO_TRENDS",
    "NestedLegs",
    "NestedLegsPattern",
    "OPPOSITE",
    "PbMark",
    "PinnedLines",
    "PinnedTrend",
    "PinnedTrends",
    "PriceAt",
    "RelationKind",
    "Side",
    "SimpleLegPattern",
    "TrendLine",
    "TrendLinesPattern",
    "TrendRelationsPattern",
    "Wick",
    "ZigZagIndidicator",
    "ZigZagPattern",
    "ZigZagPivot",
    "adjacent",
    "advancing_legs",
    "alike",
    "bar_gaps",
    "bar_positions",
    "breaks_out",
    "clear",
    "constantly",
    "dominates",
    "expands",
    "extreme_points",
    "general_direction",
    "implied_body_min",
    "leg_ends",
    "line_relations",
    "line_respects",
    "marked_bars",
    "nested_legs",
    "nests",
    "position_of",
    "price_at",
    "relations_of",
    "resolver",
    "respected_side",
    "reverses",
    "side_of",
    "split_leg_windows",
    "split_legs",
    "touches",
    "trend_lines",
    "trend_relations",
    "trim_tail",
    "undone_breakouts",
]
